name: Rust

on:
    push:
        branches: ['master']
    pull_request:
        branches: ['master']

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Build
              run: rustup target add x86_64-unknown-linux-musl

            - name: Install musl build tools
              run: sudo apt update && sudo apt install musl-tools -y
            - run: cargo check
            - run: cargo build --release --target x86_64-unknown-linux-musl --verbose
            - name: Run tests
              run: cargo test --verbose
            - name: Upload
              uses: djn24/add-asset-to-release@v2
              with:
                  token: ${{secrets.GITHUB_TOKEN}}
                  path: '/home/runner/work/diy-iot-coap-server/diy-iot-coap-server/target/x86_64-unknown-linux-musl/release/diy_iot'
